#!/usr/bin/env python3
"""
MultiArith stratified train/dev split.

Splits the 600 MultiArith CoT examples into a training source pool and a held-out
dev set, *stratified by operator-combination* so the dev distribution mirrors the
population (all 5 combos represented proportionally). The dev set is kept ORIGINAL
(never augmented); only the training source pool is later expanded by
augment_multiarith.py. Because the split is by source problem id, no dev problem
(or any of its number-variants) can leak into training.

Inputs:
    data/MultiArith.json            (600 problems w/ lEquations, lAlignments)
    data/multiarith_cot_raw.jsonl   (CoT generated by generate_cot_multiarith.py)

Outputs:
    data/multiarith_train_ids.json      train-source iIndex list (input to augment step)
    data/multiarith_dev.jsonl           original dev examples {id, question, gold_answer}
    data/multiarith_dev_prompts.txt     dev prompt-only file (--held_out_reasoning_path)
    data/multiarith_sft_train_base.txt  original train CoT in GSM8K SFT format (baseline)

Usage:
    python prepare_multiarith.py
    python prepare_multiarith.py --dev_ratio 0.15 --seed 42
"""

import argparse
import ast
import json
import os
import random
from collections import defaultdict

MULTIARITH_PATH = os.path.join("data", "MultiArith.json")
RAW_JSONL = os.path.join("data", "multiarith_cot_raw.jsonl")

TRAIN_IDS_OUT = os.path.join("data", "multiarith_train_ids.json")
DEV_JSONL_OUT = os.path.join("data", "multiarith_dev.jsonl")
DEV_PROMPTS_OUT = os.path.join("data", "multiarith_dev_prompts.txt")
SFT_TRAIN_BASE_OUT = os.path.join("data", "multiarith_sft_train_base.txt")

_OP_SYMBOL = {ast.Add: "+", ast.Sub: "-", ast.Mult: "*", ast.Div: "/"}


def operator_combo(equation: str) -> tuple:
    """Return the sorted tuple of distinct operators in an equation RHS.

    e.g. "X=((32.0+42.0)-35.0)" -> ('+', '-'). Used as the stratification key.
    """
    rhs = equation.split("=", 1)[-1]
    tree = ast.parse(rhs, mode="eval")
    ops = set()

    def walk(node):
        if isinstance(node, ast.BinOp):
            ops.add(_OP_SYMBOL[type(node.op)])
            walk(node.left)
            walk(node.right)
        elif isinstance(node, ast.UnaryOp):
            walk(node.operand)

    walk(tree.body)
    return tuple(sorted(ops))


def load_valid_records():
    """Join MultiArith problems with their CoT, keeping only valid CoT records."""
    problems = {p["iIndex"]: p for p in json.load(open(MULTIARITH_PATH, encoding="utf-8"))}

    records = []
    seen_ids = set()  # raw jsonl may contain duplicate iIndex lines; keep first only.
    with open(RAW_JSONL, encoding="utf-8") as f:
        for line in f:
            rec = json.loads(line)
            if not (rec.get("cot") and "####" in rec["cot"]):
                continue
            idx = rec["iIndex"]
            if idx not in problems or idx in seen_ids:
                continue
            seen_ids.add(idx)
            records.append({
                "iIndex": idx,
                "question": problems[idx]["sQuestion"].strip(),
                "gold_answer": problems[idx]["lSolutions"][0],
                "equation": problems[idx]["lEquations"][0],
                "cot": rec["cot"].strip(),
            })
    return records


def format_sft(rec: dict) -> str:
    return (
        f"{rec['iIndex']}\n\n"
        f"Question: {rec['question']}\n\n"
        f"Reasoning:\n{rec['cot']}\n\n"
        f"<|endoftext|>\n\n"
    )


def format_prompt_only(rec: dict) -> str:
    return (
        f"{rec['iIndex']}\n\n"
        f"Question: {rec['question']}\n\n"
        f"Reasoning:\n"
    )


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--dev_ratio", type=float, default=0.15,
                        help="Fraction held out for dev, applied per operator-combo (default 0.15).")
    parser.add_argument("--seed", type=int, default=42)
    args = parser.parse_args()

    rng = random.Random(args.seed)

    records = load_valid_records()
    print(f"Valid CoT records: {len(records)}")

    # Group by operator-combo for stratified sampling.
    by_combo = defaultdict(list)
    for rec in records:
        by_combo[operator_combo(rec["equation"])].append(rec)

    train_recs, dev_recs = [], []
    print("\nCombo            total  train   dev")
    for combo in sorted(by_combo):
        group = by_combo[combo]
        rng.shuffle(group)
        n_dev = max(1, round(len(group) * args.dev_ratio))
        dev_recs.extend(group[:n_dev])
        train_recs.extend(group[n_dev:])
        label = "".join(combo) or "none"
        print(f"  {label:<12} {len(group):>6} {len(group) - n_dev:>6} {n_dev:>5}")
    print(f"  {'TOTAL':<12} {len(records):>6} {len(train_recs):>6} {len(dev_recs):>5}")

    os.makedirs("data", exist_ok=True)

    train_ids = sorted(r["iIndex"] for r in train_recs)
    with open(TRAIN_IDS_OUT, "w", encoding="utf-8") as f:
        json.dump(train_ids, f)

    with open(DEV_JSONL_OUT, "w", encoding="utf-8") as f:
        for rec in sorted(dev_recs, key=lambda r: r["iIndex"]):
            row = {"id": rec["iIndex"], "question": rec["question"],
                   "gold_answer": rec["gold_answer"]}
            f.write(json.dumps(row, ensure_ascii=False) + "\n")

    with open(DEV_PROMPTS_OUT, "w", encoding="utf-8") as f:
        for rec in sorted(dev_recs, key=lambda r: r["iIndex"]):
            f.write(format_prompt_only(rec))

    with open(SFT_TRAIN_BASE_OUT, "w", encoding="utf-8") as f:
        for rec in sorted(train_recs, key=lambda r: r["iIndex"]):
            f.write(format_sft(rec))

    print(f"\ntrain ids   -> {TRAIN_IDS_OUT}  ({len(train_ids)})")
    print(f"dev jsonl   -> {DEV_JSONL_OUT}  ({len(dev_recs)})")
    print(f"dev prompts -> {DEV_PROMPTS_OUT}")
    print(f"train base  -> {SFT_TRAIN_BASE_OUT}")


if __name__ == "__main__":
    main()
